package sim_test

import (
	"testing"
	"time"

	"github.com/AkashiSN/node-rotation-controller/internal/policy"
	"github.com/AkashiSN/node-rotation-controller/internal/schedule"
	"github.com/AkashiSN/node-rotation-controller/internal/sim"
)

// Scenario O is the real EKS Auto Mode forceful-fallback PoC
// (test/e2e/eks-automode/SCENARIOS.md, run recorded 2026-07-12 in VALIDATION.md):
// nodepool-ff with a fixed expireAfter of 2h and terminationGracePeriod 5m, the nrc-ff
// RotationPolicy (48 windows → P = 30m, D = 28m; readyTimeout 5m, cooldownAfter 2m,
// forcefulFallback enabled), and a synchronized 12-node batch sharing one deadline.
//
// The run is the simulator's best available ground truth, so these tests replay it. What
// they pin is what the run actually pinned:
//
//   - the derivation, read live off the controller's metrics: A = 48m, t_rot = 12m,
//     t_rot_est = 10m, C = 3;
//   - the forceful-fire boundary E − t_rot = 1h48m, which the run captured to the second
//     (node 9 rotated gracefully at age 1h46m1s, node 10 went surge-less at 1h48m35s).
//
// What they deliberately do NOT pin is the 9-graceful/3-surge-less SPLIT. VALIDATION.md
// records that mix as cadence-dependent, and it was shaped by cooldownAfter being tuned
// live during the run (6m up front to hold the surplus to the deadline, dropped to 1m to
// fire it). sim takes a constant policy, so reproducing that number would mean pinning an
// artifact of manual tuning rather than controller behaviour.

// scenarioOPolicy is test/e2e/eks-automode/scenarios/nrc-ff-policy.yaml, generated by
// gen-ff-windows.sh: 48 half-hour periods with a 28-minute occurrence each.
func scenarioOPolicy(t *testing.T) *policy.Policy {
	t.Helper()
	var windows []policy.MaintenanceWindow
	for i := range 48 {
		start := i * 30
		end := start + 28
		windows = append(windows, policy.MaintenanceWindow{
			Timezone: "UTC",
			Days:     []string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"},
			Start:    hhmm(start),
			End:      hhmm(end),
		})
	}
	p := &policy.Policy{
		AgeThreshold:       "auto",
		MinRotationChances: new(2),
		MaintenanceWindows: windows,
		Surge: policy.Surge{
			MaxUnavailable:   new(1),
			ReadyTimeout:     dur(5 * time.Minute),
			CooldownAfter:    dur(2 * time.Minute),
			RetryBackoff:     dur(30 * time.Minute),
			ForcefulFallback: policy.FeatureToggle{Enabled: true},
		},
	}
	p.ApplyDefaults()
	if err := p.Validate(); err != nil {
		t.Fatalf("scenario O policy does not validate: %v", err)
	}
	return p
}

func hhmm(minutes int) string {
	return time.Date(2026, 1, 1, 0, minutes, 0, 0, time.UTC).Format("15:04")
}

// scenarioOFleet is the synchronized 12-node batch: all created 08:38:20Z, so all 12
// share the deadline 10:38:20Z. With equal deadlines and equal creation times the
// earliest-deadline order degrades to the Name tiebreak, exactly as the run observed.
func scenarioOFleet(t *testing.T) (sim.Fleet, time.Time) {
	t.Helper()
	created := mustTime(t, "2026-07-12T08:38:20Z")
	tgp := 5 * time.Minute
	f := sim.Fleet{ExpireAfter: 2 * time.Hour, TGP: &tgp}
	for _, name := range []string{
		"ff-52t8h", "ff-5rp47", "ff-94f5n", "ff-fvd7p", "ff-gjgg8", "ff-n8zqt",
		"ff-p2vdk", "ff-phmms", "ff-rnwb7", "ff-sgh57", "ff-t7sb5", "ff-tkkf7",
	} {
		f.Nodes = append(f.Nodes, sim.Node{Name: name, CreatedAt: created})
	}
	return f, created
}

// TestScenarioODerivation pins the header strip against the numbers read live off the
// controller in the recorded run: age_threshold_seconds=2880, t_rot_bound_seconds=720,
// t_rot_estimate_seconds=600, throughput_capacity=3, rotation_chances=2.
func TestScenarioODerivation(t *testing.T) {
	t.Parallel()

	f, created := scenarioOFleet(t)
	tl, err := sim.Run(scenarioOPolicy(t), f, sim.Env{}, sim.Options{
		Start: created,
		End:   created.Add(2 * time.Hour),
	})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}

	got := tl.Result
	if want := 48 * time.Minute; got.A != want {
		t.Errorf("A = %v, want %v (live metric age_threshold_seconds=2880)", got.A, want)
	}
	if want := 12 * time.Minute; got.TRot != want {
		t.Errorf("TRot = %v, want %v (live metric t_rot_bound_seconds=720)", got.TRot, want)
	}
	if want := 10 * time.Minute; got.TRotEst != want {
		t.Errorf("TRotEst = %v, want %v (live metric t_rot_estimate_seconds=600)", got.TRotEst, want)
	}
	if got.C != 3 {
		t.Errorf("C = %d, want 3 (live metric throughput_capacity=3)", got.C)
	}
	if got.G != 2 {
		t.Errorf("G = %d, want 2 (live metric rotation_chances=2)", got.G)
	}
	// The estimates that produced t_rot_est: provisioningEstimate is unset, so it resolves
	// to min(readyTimeout 5m, 5m) = 5m; drainEstimate is unset, so min(tGP 5m, 10m) = 5m.
	if want := 5 * time.Minute; got.ProvisioningEstimate != want || got.DrainEstimate != want {
		t.Errorf("estimates = prov %v / drain %v, want %v each", got.ProvisioningEstimate, got.DrainEstimate, want)
	}

	// The three feasibility warnings the run logged every pass — the designed predictors
	// of the surge-less path, not errors.
	want := map[string]bool{
		"ThroughputBurstShortfall": false,
		"ThroughputBelowArrival":   false,
		"RotationSpansNextWindow":  false,
	}
	for _, fnd := range got.Findings {
		if _, ok := want[fnd.Code]; ok {
			want[fnd.Code] = true
		}
		if fnd.Severity == schedule.Fatal {
			t.Errorf("unexpected fatal finding %s: %s", fnd.Code, fnd.Message)
		}
	}
	for code, seen := range want {
		if !seen {
			t.Errorf("finding %s missing; got %+v", code, got.Findings)
		}
	}
}

// TestScenarioOForcefulBoundary is the load-bearing regression: the graceful/surge-less
// split falls exactly on E − t_rot = 1h48m of batch age, and the fallback is entered as a
// deadline race — not as a failure.
func TestScenarioOForcefulBoundary(t *testing.T) {
	t.Parallel()

	pol := scenarioOPolicy(t)
	f, created := scenarioOFleet(t)
	originals := map[string]bool{}
	for _, n := range f.Nodes {
		originals[n.Name] = true
	}

	// Env is left at the policy's own estimates (provisioning 5m, drain 5m): the
	// self-consistent default. The horizon runs past the batch deadline so a node that
	// does not make it is visible.
	tl, err := sim.Run(pol, f, sim.Env{}, sim.Options{Start: created, End: created.Add(2*time.Hour + 10*time.Minute)})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if tl.Partial {
		t.Fatalf("Partial = true, diagnostics: %+v", tl.Diagnostics)
	}

	// boundary = deadline − t_rot: a rotation started at or after it cannot finish a
	// graceful surge in time, so decide.SurgelessFallback must take the surge-less path.
	deadline := created.Add(f.ExpireAfter)
	boundary := deadline.Add(-tl.Result.TRot) // 10:26:20Z — batch age 1h48m
	if want := created.Add(time.Hour + 48*time.Minute); !boundary.Equal(want) {
		t.Fatalf("boundary = %s, want %s (age 1h48m)", boundary, want)
	}

	var graceful, surgeless int
	for _, e := range kinds(tl.Events, sim.KindRotationStart) {
		if !originals[e.Node] {
			continue // a replacement's own rotation: outside this assertion
		}
		wantSurgeless := e.At.After(boundary) || e.At.Equal(boundary)
		if e.Surgeless != wantSurgeless {
			t.Errorf("%s started %s (batch age %v): Surgeless = %v, want %v — the boundary is %s",
				e.Node, e.At.Format(time.RFC3339), e.At.Sub(created), e.Surgeless, wantSurgeless,
				boundary.Format(time.RFC3339))
		}
		if e.Surgeless {
			surgeless++
		} else {
			graceful++
		}
	}

	// The run's shape: a MIX in one pool. The counts themselves are cadence-dependent
	// (see the comment at the top of this file), so only the mix is asserted.
	if graceful == 0 || surgeless == 0 {
		t.Errorf("graceful = %d, surge-less = %d: Scenario O is a graceful+forceful MIX in one pool", graceful, surgeless)
	}
	if total := graceful + surgeless; total > len(f.Nodes) {
		t.Errorf("the 12-node batch produced %d rotations", total)
	}

	// And the honest consequence of running the batch at the POLICY'S OWN estimates: a
	// serial surge budgeted at t_rot_est = 10m plus a 2m cooldown cannot clear 12 nodes
	// inside one 2h expireAfter, so the ones it never reaches breach. The cluster did
	// clear them — because its real provisioning and drain were far faster than the
	// estimates (see TestScenarioOEnvDrivesTheTimeline). That divergence between the
	// forecast and the world is exactly what the simulator exists to show, and a sim that
	// quietly rotated the whole batch here would be UNDER-REPORTING breaches.
	breached := kinds(tl.Events, sim.KindExpireAfterBreach)
	if len(breached) == 0 {
		t.Errorf("expire-after-breach = none, want the nodes the serial surge never reached before %s",
			deadline.Format(time.RFC3339))
	}
	// Every breach is one of the batch, at the batch's shared deadline. (A node whose
	// surge-less rotation is still draining when the deadline passes breaches too — it
	// lost the race — so breaches and rotations are not a partition of the fleet.)
	doneBefore := map[string]bool{}
	for _, e := range kinds(tl.Events, sim.KindRotationDone) {
		if e.At.Before(deadline) {
			doneBefore[e.Node] = true
		}
	}
	for _, e := range breached {
		if !originals[e.Node] {
			t.Errorf("breaching node %q is not one of the 12 originals", e.Node)
		}
		if !e.At.Equal(deadline) {
			t.Errorf("%s breached at %s, want the shared batch deadline %s", e.Node, e.At, deadline)
		}
		if doneBefore[e.Node] {
			t.Errorf("%s breached although its rotation completed before the deadline", e.Node)
		}
	}
}

// TestScenarioOEnvDrivesTheTimeline is the other half of the Env-vs-estimates contract:
// the header stays policy-derived while the timeline follows Env. Replaying the batch
// with the durations the real run actually observed (provisioning ~35s, drain ~1m17s —
// far under the 5m estimates) clears all 12 nodes with no surge-less rotation and no
// breach, which is what the cluster did.
func TestScenarioOEnvDrivesTheTimeline(t *testing.T) {
	t.Parallel()

	pol := scenarioOPolicy(t)
	f, created := scenarioOFleet(t)
	env := sim.Env{Provisioning: 35 * time.Second, Drain: 77 * time.Second}

	tl, err := sim.Run(pol, f, env, sim.Options{Start: created, End: created.Add(2 * time.Hour)})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}

	// The header strip does not move with Env: it is what the controller would compute
	// and export.
	if want := 10 * time.Minute; tl.Result.TRotEst != want {
		t.Errorf("TRotEst = %v, want %v: the header is policy-derived, not Env-derived", tl.Result.TRotEst, want)
	}
	if tl.Result.C != 3 {
		t.Errorf("C = %d, want 3: the header is policy-derived, not Env-derived", tl.Result.C)
	}

	var rotated int
	for _, e := range kinds(tl.Events, sim.KindRotationDone) {
		if e.Node == "" || e.Surgeless {
			continue
		}
		rotated++
	}
	if rotated < len(f.Nodes) {
		t.Errorf("graceful rotations completed = %d, want all %d: at the observed cadence the serial surge clears the batch before the boundary",
			rotated, len(f.Nodes))
	}
	if b := kinds(tl.Events, sim.KindExpireAfterBreach); len(b) != 0 {
		t.Errorf("expire-after-breach = %+v, want none: the recorded run had zero expired outcomes", b)
	}
}
