apiVersion: v1
kind: ConfigMap
metadata:
  name: node-rotation-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-rotation-controller.labels" . | nindent 4 }}
data:
  policy.yaml: |
    {{- toYaml .Values.config.policy | nindent 4 }}
