{{- if .Values.metrics.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-rotation-controller.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-rotation-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    {{- include "node-rotation-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
