#!/usr/bin/env bash
# Generates scenarios/nrc-ff-policy.yaml: the nrc-ff RotationPolicy with 48
# maintenanceWindows (30-min period, 28-min occurrences, all days) so the
# schedule has P=30m and WindowLen=28m => C=floor(28/(25+2))=1. Trick-free
# forceful-fallback validation (design 2026-07-04). Re-run and commit the output.
set -euo pipefail
out="$(dirname "$0")/nrc-ff-policy.yaml"
{
  cat <<'HDR'
# GENERATED by gen-ff-windows.sh — do not hand-edit; re-run the script.
# nrc-ff governs nodepool-ff (ff-scope) for the trick-free forceful-fallback
# scenario (SCENARIOS.md Scenario O). ageThreshold is auto (E fixed at 2h is
# never patched); 48 windows give P=30m so the K*P=1h grace lets a few graceful
# surges run before the synchronized batch's surplus fires surge-less.
apiVersion: noderotation.io/v1alpha1
kind: RotationPolicy
metadata:
  name: nrc-ff
spec:
  nodePoolSelector:
    matchLabels:
      noderotation-ff/in-scope: "true"
  ageThreshold: auto
  minRotationChances: 2
  surge:
    maxUnavailable: 1
    readyTimeout: 5m
    cooldownAfter: 2m
    retryBackoff: 30m
    matchNodeRequirements:
      required:
        - topology.kubernetes.io/zone
        - kubernetes.io/arch
        - karpenter.sh/capacity-type
      preferred: []
    forcefulFallback:
      enabled: true
  prePull:
    enabled: false
  maintenanceWindows:
HDR
  for i in $(seq 0 47); do
    start=$((i * 30)); end=$((start + 28))
    printf '    - timezone: UTC\n'
    printf '      days: [Mon, Tue, Wed, Thu, Fri, Sat, Sun]\n'
    printf '      start: "%02d:%02d"\n' $((start / 60)) $((start % 60))
    printf '      end: "%02d:%02d"\n' $((end / 60)) $((end % 60))
  done
} > "$out"
echo "wrote $out"
