#!/usr/bin/env bash
# Generates scenarios/nrc-soak-policy.yaml and scenarios/nrc-soak-epi-policy.yaml
# for the Scenario P tight-race soak (issue #118). 48 maintenanceWindows (30-min
# period, 28-min occurrences, all days) give P=30m, D=28m => auto A = E(2h12m) −
# (K·P + t_rot) = 1h and C = ceil(28/(t_rot_est 10m + cooldown 2m)) = 3. The 2m
# idle gap < 12m makes the RotationSpansNextWindow warn structurally unavoidable
# — it is the scenario's single expected finding. forcefulFallback is ARMED on
# both policies: the main-soak PASS asserts it never fires; the epi pool
# deterministically fires it once (frozen hold-and-release). Re-run and commit.
set -euo pipefail
dir="$(dirname "$0")"
emit() { # $1=policy name  $2=selector label key  $3=output file
  local name="$1" label="$2" out="$3"
  {
    cat <<HDR
# GENERATED by gen-soak-windows.sh — do not hand-edit; re-run the script.
# ${name}: Scenario P (issue #118) tight-race soak policy (SCENARIOS.md).
# ageThreshold is auto: A = E(2h12m) − leadTime(2·30m + 12m) = 1h.
apiVersion: noderotation.io/v1alpha1
kind: RotationPolicy
metadata:
  name: ${name}
spec:
  nodePoolSelector:
    matchLabels:
      ${label}: "true"
  ageThreshold: auto
  minRotationChances: 2
  surge:
    maxUnavailable: 1
    readyTimeout: 5m
    cooldownAfter: 2m
    retryBackoff: 30m
    matchNodeRequirements:
      required:
        - topology.kubernetes.io/zone
        - kubernetes.io/arch
        - karpenter.sh/capacity-type
      preferred: []
    forcefulFallback:
      enabled: true
  prePull:
    enabled: false
  maintenanceWindows:
HDR
    for i in $(seq 0 47); do
      start=$((i * 30)); end=$((start + 28))
      printf '    - timezone: UTC\n'
      printf '      days: [Mon, Tue, Wed, Thu, Fri, Sat, Sun]\n'
      printf '      start: "%02d:%02d"\n' $((start / 60)) $((start % 60))
      printf '      end: "%02d:%02d"\n' $((end / 60)) $((end % 60))
    done
  } > "$out"
  echo "wrote $out"
}
emit nrc-soak     noderotation-soak/in-scope     "$dir/nrc-soak-policy.yaml"
emit nrc-soak-epi noderotation-soak-epi/in-scope "$dir/nrc-soak-epi-policy.yaml"
