#!/usr/bin/env bash
# Scenario P analysis dry-run (spec rev4 §3.2): builds synthetic run-dirs
# (controller.log, snapshots.jsonl, scrape.log) with known-by-construction
# answers, runs soak-analyze.py against them, and asserts the reports match —
# proving the analyzer works BEFORE the real 12h run produces any data.
#
# Case 1: 3 rotations at margins +70m/+45m/+0.5m; a counter reset mid-stream on
#         one scraped pod; an absent `expired` series (must read as 0, not
#         crash); a SCRAPE_ERROR line; a seq gap; a clean end-census (young
#         right-censored replacement claims, no stale/failed claims).
# Case 3a: a REAL zap console-format (--zap-devel) "rotation complete" line —
#         the analyzer must parse ZERO ledger entries but warn LOUDLY instead
#         of silently reporting an empty ledger.
# Case 3b: a REAL zap production-JSON "rotation complete" line — must parse.
#         Both real lines were generated by a Go probe using this repo's own
#         logger wrapper (sigs.k8s.io/controller-runtime/pkg/log/zap) with the
#         exact kv shape of rotation_controller.go:1168.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
analyze="$here/soak-analyze.py"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

die() { echo "FIXTURE FAIL: $*" >&2; exit 1; }
# assert_in <file> <description> <exact-text>
assert_in() { grep -qF "$3" "$1" || die "$2 — missing expected text in $1: $3"; }
# assert_not_in <file> <description> <exact-text>
assert_not_in() { grep -qF "$3" "$1" && die "$2 — unexpected text in $1: $3" || true; }

# ===========================================================================
# Case 1 — margins, counter reset, absent series, SCRAPE_ERROR, seq gap
# ===========================================================================
run="$tmp/case1"; mkdir -p "$run"

# Births: nc-1 @ T, nc-2 @ T+5m, nc-3 @ T+10m (T = 2026-07-14T00:00:00Z). An
# error-line and a duplicate-kind decoy line exercise the skip paths. The LAST
# nodeclaims snapshot (the criterion-9 census) shows the 3 old claims already
# gone, replaced by 2 young claims — right-censored, must not be flagged.
cat > "$run/snapshots.jsonl" <<'EOF'
{"ts":"2026-07-14T00:11:00Z","kind":"nodeclaims","items":[{"metadata":{"name":"nc-1","creationTimestamp":"2026-07-14T00:00:00Z","labels":{"karpenter.sh/nodepool":"nodepool-soak"},"annotations":{}}},{"metadata":{"name":"nc-2","creationTimestamp":"2026-07-14T00:05:00Z","labels":{"karpenter.sh/nodepool":"nodepool-soak"},"annotations":{}}},{"metadata":{"name":"nc-3","creationTimestamp":"2026-07-14T00:10:00Z","labels":{"karpenter.sh/nodepool":"nodepool-soak"},"annotations":{}}}]}
{"ts":"2026-07-14T00:13:00Z","kind":"nodeclaims","error":true}
{"ts":"2026-07-14T00:20:00Z","kind":"pods","items":[]}
{"ts":"2026-07-14T02:25:00Z","kind":"nodeclaims","items":[{"metadata":{"name":"nc-1b","creationTimestamp":"2026-07-14T02:20:00Z","labels":{"karpenter.sh/nodepool":"nodepool-soak"},"annotations":{}}},{"metadata":{"name":"nc-2b","creationTimestamp":"2026-07-14T02:21:00Z","labels":{"karpenter.sh/nodepool":"nodepool-soak"},"annotations":{}}}]}
EOF

# kubectl logs --prefix --timestamps shape: "[pod/x] <k8s-ts> <stdout-line>",
# with soak-record.sh's own "== <ts> (re)start:" headers interleaved. Margins:
#   nc-1: deadline 00:00:00+7920s=02:12:00Z, completion 01:02:00Z -> +70m
#   nc-2: deadline 00:05:00+7920s=02:17:00Z, completion 01:32:00Z -> +45m
#   nc-3: deadline 00:10:00+7920s=02:22:00Z, completion 02:21:30Z -> +0.5m
cat > "$run/controller.log" <<'EOF'
== 2026-07-14T00:00:00Z (re)start: kubectl logs -n node-rotation-system -f -l app.kubernetes.io/name=node-rotation-controller --all-containers --prefix --timestamps --tail=-1
[pod/node-rotation-controller-0] 2026-07-14T01:02:00.100000000Z {"level":"info","ts":"2026-07-14T01:02:00Z","msg":"rotation complete","nodeclaim":"nc-1","nodepool":"nodepool-soak","mode":"surge","surgeNode":"ip-10-0-1-11","surgeWait":"1m30s","drain":"4m0s","total":"5m30s"}
[pod/node-rotation-controller-0] 2026-07-14T01:32:00.100000000Z {"level":"info","ts":"2026-07-14T01:32:00Z","msg":"rotation complete","nodeclaim":"nc-2","nodepool":"nodepool-soak","mode":"surge","surgeNode":"ip-10-0-1-12","surgeWait":"1m0s","drain":"3m0s","total":"4m0s"}
[pod/node-rotation-controller-0] 2026-07-14T02:21:30.100000000Z {"level":"info","ts":"2026-07-14T02:21:30Z","msg":"rotation complete","nodeclaim":"nc-3","nodepool":"nodepool-soak","mode":"surge","surgeNode":"ip-10-0-1-13","surgeWait":"1m0s","drain":"2m0s","total":"3m0s"}
EOF

# Two pods. pod-a's success counter resets mid-stream (seq2 8 -> seq4 2): the
# reset-tolerant delta sum must still add the post-reset epoch rather than
# drop or negate it. seq 3 is entirely absent (gap). One SCRAPE_ERROR line.
# `expired` has zero lines anywhere -> must read as 0, not crash.
#
#   pod-a success: 5(seq1) 8(seq2) [reset] 2(seq4) 6(seq5) -> deltas 5+3+2+4=14
#   pod-a failure: 0 1 1 1                                 -> deltas 0+1+0+0=1
#   pod-b success: 0(seq1) [error@seq2] 3(seq4) 3(seq5)     -> deltas 0+3+0=3
#   totals: success=17 failure=1 expired=0 (absent) forceful_fallback=0 (absent)
cat > "$run/scrape.log" <<'EOF'
1 2026-07-14T01:00:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 5
1 2026-07-14T01:00:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="failure"} 0
1 2026-07-14T01:00:00Z pod-b noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 0
2 2026-07-14T01:01:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 8
2 2026-07-14T01:01:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="failure"} 1
2 2026-07-14T01:01:00Z pod-b SCRAPE_ERROR proxy
4 2026-07-14T01:04:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 2
4 2026-07-14T01:04:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="failure"} 1
4 2026-07-14T01:04:00Z pod-b noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 3
5 2026-07-14T01:05:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 6
5 2026-07-14T01:05:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="failure"} 1
5 2026-07-14T01:05:00Z pod-b noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 3
EOF

python3 "$analyze" "$run" > "$run/stdout.log" 2> "$run/stderr.log" \
  || die "case1: analyzer exited non-zero: $(cat "$run/stdout.log" "$run/stderr.log")"
[ -f "$run/report.md" ] || die "case1: report.md was not written"

assert_in "$run/report.md" "case1 rotation count" "rotations (ledger): 3"
assert_in "$run/report.md" "case1 margin distribution" "min=0.5m median=45.0m max=70.0m"
assert_in "$run/report.md" "case1 criterion 1 expired PASS" "| 1 expired==0 | 0 | PASS |"
assert_in "$run/report.md" "case1 success survives the reset (pod-a 14 + pod-b 3)" "success=17"
assert_in "$run/report.md" "case1 seq gap reported" "seq 3-3 missing"
assert_in "$run/report.md" "case1 criterion 8 margins PASS" "| 8 all margins>0 | min 0.5m | PASS |"
assert_in "$run/report.md" "case1 criterion 9 census clean (young replacements right-censored)" "| 9 end census (claims: stale/failed) | 0 stale, 0 failed | PASS |"
assert_not_in "$run/report.md" "case1 must not warn about console logs" "0 lines parsed as ledger entries"

# ===========================================================================
# Case 2 — the runbook's EXACT harvest order: current log first, `--previous`
#          APPENDED after it (SCENARIOS.md Harvest step)
# ===========================================================================
# In file order the older epoch's LOWER counter values follow the newer
# epoch's higher ones; processed naively that reads as a controller counter
# reset and double-counts (18 would become 30), and the duplicated seq
# numbers would mask the scraper restart. The analyzer must chronologically
# sort by ts first, report the restart explicitly, and keep the wall-clock
# gap logic intact across it.
#
# True chronology (all pod-a, controller counters continuous — NO reset):
#   previous epoch: seq1@01:00 v10, seq2@01:01 v12, [seq3 missing], seq4@01:03 v14
#   scraper restarts (downtime 01:03 -> 01:06 = 180s, under the 5m rule)
#   current epoch:  seq1@01:06 v15, seq2@01:07 v18
# Correct total: 10+2+2+1+3 = 18 (the final counter value). File-order bug: 30.
run2="$tmp/case2"; mkdir -p "$run2"
cat > "$run2/snapshots.jsonl" <<'EOF'
{"ts":"2026-07-14T01:10:00Z","kind":"nodeclaims","items":[{"metadata":{"name":"nc-young","creationTimestamp":"2026-07-14T01:00:00Z","labels":{"karpenter.sh/nodepool":"nodepool-soak"},"annotations":{}}}]}
EOF
: > "$run2/controller.log"
cat > "$run2/scrape.log" <<'EOF'
1 2026-07-14T01:06:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 15
2 2026-07-14T01:07:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 18
1 2026-07-14T01:00:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 10
2 2026-07-14T01:01:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 12
4 2026-07-14T01:03:00Z pod-a noderotation_completed_total{nodepool="nodepool-soak",outcome="success"} 14
EOF

python3 "$analyze" "$run2" > "$run2/stdout.log" 2> "$run2/stderr.log" \
  || die "case2: analyzer exited non-zero: $(cat "$run2/stdout.log" "$run2/stderr.log")"
assert_in "$run2/report.md" "case2 counters NOT double-counted across the appended --previous epoch" "success=18"
assert_in "$run2/report.md" "case2 scraper restart reported explicitly" "scraper restart at 2026-07-14T01:06:00Z (seq 4 -> 1"
assert_in "$run2/report.md" "case2 in-epoch wall-clock gap logic unaffected" "seq 3-3 missing"
assert_in "$run2/report.md" "case2 criterion 5 counts the restart but passes (both gaps under 5m)" \
  "| 5 scraper seq contiguous | 1 gap(s), 0 over 5m, 1 restart(s), 0 SCRAPE_ERROR | PASS |"

# ===========================================================================
# Case 3a — REAL --zap-devel console line: zero ledger entries + LOUD warning
# ===========================================================================
# The console line's trailing {...} IS valid JSON (so json.loads succeeds) but
# carries only the kv fields — no "msg"/"ts" — which is exactly why a run
# installed with logging.development: true silently loses every rotation
# unless the analyzer warns. Line generated verbatim by the zap probe; tabs
# are literal (printf '\t').
run3a="$tmp/case3a"; mkdir -p "$run3a"
cat > "$run3a/snapshots.jsonl" <<'EOF'
{"ts":"2026-07-14T13:00:00Z","kind":"nodeclaims","items":[{"metadata":{"name":"nc-1","creationTimestamp":"2026-07-14T11:00:00Z","labels":{"karpenter.sh/nodepool":"nodepool-soak"},"annotations":{"noderotation.io/state":"draining"}}}]}
EOF
printf '[pod/node-rotation-controller-0] 2026-07-14T12:45:44.000000000Z 2026-07-14T21:45:44+09:00\tINFO\trotation complete\t{"nodepool": "nodepool-soak", "nodeclaim": "nc-1", "mode": "surge", "surgeNode": "ip-10-0-1-11", "surgeWait": "1m30s", "drain": "4m0s", "total": "5m30s"}\n' > "$run3a/controller.log"
: > "$run3a/scrape.log"

python3 "$analyze" "$run3a" > "$run3a/stdout.log" 2> "$run3a/stderr.log" \
  || die "case3a: analyzer exited non-zero: $(cat "$run3a/stdout.log" "$run3a/stderr.log")"
assert_in "$run3a/report.md" "case3a ledger must be empty on console-format logs" "rotations (ledger): 0"
assert_in "$run3a/report.md" "case3a report must carry the console-format warning" "but 0 lines parsed as ledger entries"
assert_in "$run3a/report.md" "case3a warning must name the likely cause" "logging.development: true"
assert_in "$run3a/stderr.log" "case3a warning must also go to stderr" "but 0 lines parsed as ledger entries"

# ===========================================================================
# Case 3b — REAL production-JSON line (same probe): must parse into the ledger
# ===========================================================================
run3b="$tmp/case3b"; mkdir -p "$run3b"
cat > "$run3b/snapshots.jsonl" <<'EOF'
{"ts":"2026-07-14T13:00:00Z","kind":"nodeclaims","items":[{"metadata":{"name":"nc-1","creationTimestamp":"2026-07-14T11:00:00Z","labels":{"karpenter.sh/nodepool":"nodepool-soak"},"annotations":{}}}]}
EOF
cat > "$run3b/controller.log" <<'EOF'
[pod/node-rotation-controller-0] 2026-07-14T12:45:44.000000000Z {"level":"info","ts":"2026-07-14T21:45:44+09:00","msg":"rotation complete","nodepool":"nodepool-soak","nodeclaim":"nc-1","mode":"surge","surgeNode":"ip-10-0-1-11","surgeWait":"1m30s","drain":"4m0s","total":"5m30s"}
EOF
: > "$run3b/scrape.log"

python3 "$analyze" "$run3b" > "$run3b/stdout.log" 2> "$run3b/stderr.log" \
  || die "case3b: analyzer exited non-zero: $(cat "$run3b/stdout.log" "$run3b/stderr.log")"
# birth 11:00:00Z + 7920s = 13:12:00Z deadline; completion 21:45:44+09:00 =
# 12:45:44Z -> margin 26m16s = 26.3m (also proves offset-bearing ts parses).
assert_in "$run3b/report.md" "case3b prod-JSON line parses into the ledger" "rotations (ledger): 1"
assert_in "$run3b/report.md" "case3b margin from the offset-bearing real ts" "min=26.3m"
assert_not_in "$run3b/report.md" "case3b must not warn" "0 lines parsed as ledger entries"
# The census snapshot deliberately still shows nc-1 at age 7200s > A with no
# in-flight state: the flagged-stale path must render (name, pool, age, state).
assert_in "$run3b/report.md" "case3b stale claim rendered with its state" "nc-1 (pool=nodepool-soak, age=7200s, state=(none))"

echo "fixture ok"
