//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureToggle) DeepCopyInto(out *FeatureToggle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureToggle.
func (in *FeatureToggle) DeepCopy() *FeatureToggle {
	if in == nil {
		return nil
	}
	out := new(FeatureToggle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchNodeRequirements) DeepCopyInto(out *MatchNodeRequirements) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Preferred != nil {
		in, out := &in.Preferred, &out.Preferred
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchNodeRequirements.
func (in *MatchNodeRequirements) DeepCopy() *MatchNodeRequirements {
	if in == nil {
		return nil
	}
	out := new(MatchNodeRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationPolicy) DeepCopyInto(out *RotationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationPolicy.
func (in *RotationPolicy) DeepCopy() *RotationPolicy {
	if in == nil {
		return nil
	}
	out := new(RotationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RotationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationPolicyList) DeepCopyInto(out *RotationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RotationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationPolicyList.
func (in *RotationPolicyList) DeepCopy() *RotationPolicyList {
	if in == nil {
		return nil
	}
	out := new(RotationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RotationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationPolicySpec) DeepCopyInto(out *RotationPolicySpec) {
	*out = *in
	if in.NodePoolSelector != nil {
		in, out := &in.NodePoolSelector, &out.NodePoolSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MinRotationChances != nil {
		in, out := &in.MinRotationChances, &out.MinRotationChances
		*out = new(int32)
		**out = **in
	}
	if in.MaintenanceWindows != nil {
		in, out := &in.MaintenanceWindows, &out.MaintenanceWindows
		*out = make([]MaintenanceWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Surge.DeepCopyInto(&out.Surge)
	out.PrePull = in.PrePull
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationPolicySpec.
func (in *RotationPolicySpec) DeepCopy() *RotationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RotationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationPolicyStatus) DeepCopyInto(out *RotationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationPolicyStatus.
func (in *RotationPolicyStatus) DeepCopy() *RotationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RotationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Surge) DeepCopyInto(out *Surge) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int32)
		**out = **in
	}
	if in.ReadyTimeout != nil {
		in, out := &in.ReadyTimeout, &out.ReadyTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.CooldownAfter != nil {
		in, out := &in.CooldownAfter, &out.CooldownAfter
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RetryBackoff != nil {
		in, out := &in.RetryBackoff, &out.RetryBackoff
		*out = new(v1.Duration)
		**out = **in
	}
	in.MatchNodeRequirements.DeepCopyInto(&out.MatchNodeRequirements)
	out.ForcefulFallback = in.ForcefulFallback
	if in.DrainEstimate != nil {
		in, out := &in.DrainEstimate, &out.DrainEstimate
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Surge.
func (in *Surge) DeepCopy() *Surge {
	if in == nil {
		return nil
	}
	out := new(Surge)
	in.DeepCopyInto(out)
	return out
}
